service: coffee-shop-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    ORDERS_TABLE: orders-${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - Fn::GetAtt: [OrdersTable, Arn]

functions:
  createOrder:
    handler: handlers/createOrder.handler
    events:
      - http:
          path: orders
          method: post

  getOrder:
    handler: handlers/getOrder.handler
    events:
      - http:
          path: orders/{id}
          method: get

  listOrders:
    handler: handlers/listOrders.handler
    events:
      - http:
          path: orders
          method: get
 
